### ISSUE TITLE
Cannot get the breadcrumb plugin to work

### ISSUE THREAD

**Issue by gosdenj** [getgrav/grav-plugin-breadcrumbs#1]
Hello,

I've followed the instructions, but the breadcrumb plugin isn't working. I'm running Grav 0.9.2.

Any help would be really appreciated.

Thanks,
Jeff

**Comment by EZTEQ** [comment]
Same problem over here. Using **Antimatter** and copied **breadcrumbs.yaml** to **user/config/plugins/breadcrumbs.yaml**.
```yaml
enabled: true
show_all: true
built_in_css: true
include_home: true
icon_home: ''
icon_divider_classes: 'fa fa-angle-right'
link_trailing: false
```

The error log is empty.
